[package]
name = "sdk"
version = "0.1.0"
edition = "2021"


[build-dependencies]
bindgen = "0.69.4"

[dependencies]
serde_json = "1.0.118"
serde = { version = "1.0.203", features = ["derive"] }
thiserror = "1.0.61"
anyhow = "1.0"
